### ISSUE TITLE
Parser package conflict when using client in same project

### ISSUE THREAD

**Issue by kgecici** [trinopoty/socket.io-server-java#27]
Hi

I created test project to check our use cases with socket.io official client 2.0.1 and socket.io-server-java. 

Since following classes with client same package, it causes conflict :(

https://github.com/socketio/engine.io-client-java/blob/master/src/main/java/io/socket/engineio/parser/Parser.java
https://github.com/socketio/engine.io-server-java/blob/master/engine.io-server/src/main/java/io/socket/engineio/parser/Parser.java

Would you consider changing Parser package at server (or client?)

Error stack trace:
java.lang.IncompatibleClassChangeError: Method 'void io.socket.engineio.parser.Parser.decodePayload(java.lang.String, io.socket.engineio.parser.Parser$DecodePayloadCallback)' must be InterfaceMethodref constant
	at io.socket.engineio.client.transports.Polling._onData(Polling.java:131)
	at io.socket.engineio.client.transports.Polling.onData(Polling.java:101)
	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:117)
	at io.socket.thread.EventThread$2.run(EventThread.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Exception in thread "EventThread" java.lang.IncompatibleClassChangeError: Method 'void io.socket.engineio.parser.Parser.decodePayload(java.lang.String, io.socket.engineio.parser.Parser$DecodePayloadCallback)' must be InterfaceMethodref constant
	at io.socket.engineio.client.transports.Polling._onData(Polling.java:131)
	at io.socket.engineio.client.transports.Polling.onData(Polling.java:101)
	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:117)
	at io.socket.thread.EventThread$2.run(EventThread.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by trinopoty** [comment]
Unfortunately, since I've kept the same class and package name but modified the code, there's no solution to this issue.
I didn't imagine both the client and server libraries being used in the same project.
I'll update the package name and publish a new version. That should fix the issue.

**Comment by trinopoty** [comment]
I've published version 4.0.0 to maven and it should be available in a few hours. This version fixes the conflicting packages issue.
There are also some restructure to the packages, particularly around the `Emitter` class that you'll need to patch in your source code.
